# Generated by Django 5.1.3 on 2024-12-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='end_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='start_dt',
            field=models.DateTimeField(default="2024-12-08T00:00:00"),
            preserve_default=False,
        ),
    ]
