# Generated by Django 5.1.3 on 2024-12-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_exhibition_end_dt_exhibition_start_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='end_dt',
            field=models.DateTimeField(default='2024-12-08T00:00:00'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_dt',
            field=models.DateTimeField(default='2024-12-08T00:00:00'),
        ),
    ]
