# Generated by Django 5.1.3 on 2024-12-08 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0006_alter_exhibition_end_dt_alter_exhibition_start_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='end_dt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
